platform :ios, '9.0'

inhibit_all_warnings!

use_frameworks!

target 'huanleSong' do
    pod 'SVProgressHUD'
    pod 'YYKit'
    pod 'Masonry'
    pod 'IQKeyboardManager'
    pod 'MJRefresh'
    pod 'ReactiveObjC'
    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'FreeStreamer','~> 3.7.2'
    pod 'HPGrowingTextView', '~>1.1'


end

